project_name: go-hmccu-examples

before:
  hooks:
    - go mod tidy

builds:
  - main: ./examples/device-info
    binary: device-info
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
      # all Raspberry Pi versions
      - linux_arm_6

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      mode: 0755

changelog:
  skip: true

release:
  github:
    owner: mdzio
    name: go-hmccu
  draft: true
